### ISSUE TITLE
Problem with '\' file when cloning on Windows

### ISSUE THREAD

**Issue by LedaguenelArthur** [KareemYousrii/SPL#1]
Hi,

I tried cloning this repository on my Windows PC and I got this error :
`error: invalid path 'C-HMCNN/hmc-utils/pypsdd/pypsdd/\'`

I believe that the '\\' file in PySDD is causing troubles for Windows to clone because the character '\\' is not allowed in file names under Windows.

Is this specific name useful in any way or could it be changed ?

Best regards,
Arthur Ledaguenel

**Comment by KareemYousrii** [comment]
Hi Arthur,

We should be using the OS agnostic os.join instead of the unix-specific forward slash, which is, I believe, what is causing the issue. I will push a fix as soon as possible. In the mean time, you can fix the issue by simply replacing the path using the correct one under Windows.

**Comment by LedaguenelArthur** [comment]
Hi @KareemYousrii,

I think I can't even clone the project as long as there is a file named "\\", am I doing something wrong ? I think the only option to copy the repo as is would be to download the zip folder and modify the file name by hand. Is that what you were suggesting me ? Because I am not sure where switching to `os.join` would make a difference for cloning the repo.

Best regards,
Arthur

**Comment by KareemYousrii** [comment]
Oh I see, I misunderstood the problem. I have deleted the file, hopefully that fixes the issue.

**Comment by LedaguenelArthur** [comment]
Hi,
I've seen you deleted the file, the cloning works perfectly now, thank you !
