### ISSUE TITLE
dataset error

### ISSUE THREAD

**Issue by zwxu064** [KareemYousrii/SPL#2]
For warcraft dataset, I have downloaded 12_by_12/train_maps.npy, 12_by_12/train_shortest_paths.npy, etc, but how do I generate constraint_trimmed.vtree? "no such file 'data/warcraft_shortest_path/12_by_12/constraint_trimmed.vtree'", this is an immediate error when I run ./run_product.sh

**Comment by LedaguenelArthur** [comment]
Hi @zwxu064,

Could I know where you found the dataset files ?

Best regards,
Arthur

**Comment by LedaguenelArthur** [comment]
Hi @KareemYousrii,

Where could I find the dataset files 12_by_12/train_maps.npy, 12_by_12/train_shortest_paths.npy, etc. ?

Best regards,
Arthur Ledaguenel

**Comment by JLUpengjiaji** [comment]
Hello sir, have you successfully run the grids part of this project? This code seems to have many errors

**Comment by zwxu064** [comment]
> Hi @zwxu064,
> 
> Could I know where you found the dataset files ?
> 
> Best regards, Arthur

Hi, sorry for being replying late, I just notice this message.

If you are still looking for this dataset, it is from https://edmond.mpg.de/dataset.xhtml?persistentId=doi:10.17617/3.YJCQ5S that used in this paper's repository, https://github.com/martius-lab/blackbox-differentiation-combinatorial-solvers?tab=readme-ov-file.

I am no longer using this repository but datasets from another one, https://github.com/archettialberto/tilebased_navigation_datasets which has pokemon as well.

**Comment by zwxu064** [comment]
> Hello sir, have you successfully run the grids part of this project? This code seems to have many errors

Hi, I am no longer using this repository, the previously question is the missing constraint_trimmed.vtree, but I find there is one in WarcraftShortestPath/data/constraint_trimmed.vtree.

Not sure if it will work, have not yet checked.

**Comment by zwxu064** [comment]
I will close this issue because it has been a while. I am no longer using this repository, but free feel to leave any comments.
